// <auto-generated />
using System;
using AHutak.Rbac.Core.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AHutak.TestWebApiApplication.Migrations
{
    [DbContext(typeof(RbacDbContext))]
    partial class RbacDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rbac")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AHutak.Rbac.Core.Abstractions.Entities.PermissionAssignment", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("_id");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionAssignments", "rbac");
                });

            modelBuilder.Entity("AHutak.Rbac.Core.Abstractions.Entities.Role", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Roles", "rbac");
                });

            modelBuilder.Entity("AHutak.Rbac.Core.Abstractions.Entities.SimplePermission", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Permissions", "rbac");
                });

            modelBuilder.Entity("AHutak.Rbac.Core.Abstractions.Entities.UserAssignment", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_id");

                    b.HasIndex("RoleId");

                    b.ToTable("UserAssignments", "rbac");
                });

            modelBuilder.Entity("AHutak.Rbac.Core.Abstractions.Entities.PermissionAssignment", b =>
                {
                    b.HasOne("AHutak.Rbac.Core.Abstractions.Entities.Role", null)
                        .WithMany("PermissionAssignments")
                        .HasForeignKey("RoleId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AHutak.Rbac.Core.Abstractions.Entities.UserAssignment", b =>
                {
                    b.HasOne("AHutak.Rbac.Core.Abstractions.Entities.Role", null)
                        .WithMany("UserAssignments")
                        .HasForeignKey("RoleId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AHutak.Rbac.Core.Abstractions.Entities.Role", b =>
                {
                    b.Navigation("PermissionAssignments");

                    b.Navigation("UserAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
